### ISSUE TITLE
Conda colab everything

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/WorkshopMDMLEdinburgh2022#2]
For the notebooks to work on colab we'll have to work out how to deal with installing dependencies. The best approach I know to deal with this (and least prone to failing on us randomly) is to use [condacolab](https://github.com/conda-incubator/condacolab).

I've already started doing this for the MD notebooks: https://github.com/MDAnalysis/WorkshopMDMLEdinburgh2022/pulls but we should add it to the ML ones too if needed. @degiacom @ppxasjsm are there any dependencies in your notebooks that aren't provided in the standard colab environment? If so I'm happy to add them in once the notebooks are complete.

**Comment by degiacom** [comment]
Thank you @IAlibay! For my ML notebooks I would need nglview and scikit-learn.

**Comment by IAlibay** [comment]
> Thank you @IAlibay! For my ML notebooks I would need nglview and scikit-learn.

Ok, is it already finished? Otherwise I can wait until later today / tomorrow to add things.

**Comment by degiacom** [comment]
The notebook ML\ML_RF_03.ipynb (the one needing nglview) is finished, ML\ML_NN_04.ipynb still in preparation.

**Comment by degiacom** [comment]
Sorry, that was left there by accident (that was a temporary hack to reformat the multiPDB files so that MDAnalysis can read them). I have removed it now!

**Comment by degiacom** [comment]
That notebook is finished. Some minor tweaks on text may be required, but content will not change. Remaining issues are dependencies on nglview and  MDAnalysis (had not mentioned the latter previously, sorry!), and inability to load PDB files from data folder (see #4).

**Comment by IAlibay** [comment]
Ok thanks for the update @degiacom - I'll update 03 with the Colab fix when I arrive in Edinburgh. Let me know when the others are ready and we can copy paste things over to them too.

**Comment by IAlibay** [comment]
All fixed.
