### ISSUE TITLE
Alanine dipeptide data cannot be obtained over colab

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/WorkshopMDMLEdinburgh2022#4]
In `ML_clustering_01` - `data = np.load('data/alanine-dipeptide-3x250ns-backbone-dihedrals.npz', mmap_mode='r')`

The data folder isn't local to the colab instance, so you can't load from it. You probably need to fetch via wget?

**Comment by richardjgowers** [comment]
We can probably push this up to MDAnalysisData quick enough?

**Comment by IAlibay** [comment]
it's an npz so probably not?

**Comment by IAlibay** [comment]
For all notebooks that require this, I propose adding this additional cell in the "colab setup" sections of the notebooks:

```
# NBVAL_SKIP
# copy over data repository
!if [ -n "$COLAB_GPU" ]; then git clone https://github.com/MDAnalysis/WorkshopMDMLEdinburgh2022.git; fi
!if [ -n "$COLAB_GPU" ]; then cp -r WorkshopMDMLEdinburgh2022/ML/data .; fi
```

It's not the nicest fix, but it works.

**Comment by richardjgowers** [comment]
This seems like the easiest fix tbh

**Comment by degiacom** [comment]
Currently, same problem in `ML_RF_03`. There are three PDB files for MDAnalysis to load, in data folder (first call is `universe_open = mda.Universe(f'{folder}MurD_open_backbone.pdb')`, where `folder = data/`).

**Comment by IAlibay** [comment]
Right I've pushed fixes to 03 and 01 that should fix both for colab. I'll push similar changes to 02 and 04. I'm not sure about their status so I'm doing them in independent commits, please revert changes if I'm stepping on folks' ongoing work.

**Comment by IAlibay** [comment]
Nevermind, I'll hold off on 02 and 04 since there's a few incomplete cells and I might as well add things & test after it's all done.

**Comment by IAlibay** [comment]
This is fixed as far as I'm aware, closing as such.
